sudo: required
services:
  - docker

before_install:
  - docker build -t jrogatis/frontEndDockerComposeEx -f Dockerfile.dev .

script:
  - docker run jrogatis/frontEndDockerComposeEx npm run test -- --coverage
