sudo: required
services:
  - docker

before_install:
  - docker build -t jrogatis/frontend -f Dockerfile.dev .

script:
  - docker run jrogatis/frontend npm run test

deploy:
  provider: elasticbeanstalk
  region: 'sa-east-1'
  app: 'docker-react'
  env: 'DockerReact-env'
  bucket_name: 'elasticbeanstalk-sa-east-1-397412133666'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
